# This is a basic workflow to help you get started with Actions

name: leetcode_synchronizer

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Run LeetCode Synchronizer
        uses: dos-m0nk3y/LeetCode-Synchronizer@v1.1.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
